<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="28001" started-at="2016-11-09T13:13:22Z" finished-at="2016-11-09T13:13:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="28001" started-at="2016-11-09T13:13:22Z" finished-at="2016-11-09T13:13:50Z">
      <class name="br.com.cagece.prax.automatizacao.srv001.Srv001RevisaoDadosCadastraisProcedente">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:br.com.cagece.prax.automatizacao.srv001.Srv001RevisaoDadosCadastraisProcedente@64cd705f]" name="setUp" is-config="true" duration-ms="0" started-at="2016-11-09T10:13:22Z" finished-at="2016-11-09T10:13:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[TIMEOUT]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: TIMEOUT
	at org.testng.Assert.fail(Assert.java:94)
	at pages.validacao.ValidacaoAtendimento.validarTeste(ValidacaoAtendimento.java:786)
	at auxiliares.ServiceTestBase.setUp(ServiceTestBase.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:601)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="executar()[pri:0, instance:br.com.cagece.prax.automatizacao.srv001.Srv001RevisaoDadosCadastraisProcedente@64cd705f]" name="executar" duration-ms="0" started-at="2016-11-09T10:13:50Z" finished-at="2016-11-09T10:13:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executar -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:br.com.cagece.prax.automatizacao.srv001.Srv001RevisaoDadosCadastraisProcedente@64cd705f]" name="afterMethod" is-config="true" duration-ms="0" started-at="2016-11-09T10:13:50Z" finished-at="2016-11-09T10:13:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- br.com.cagece.prax.automatizacao.srv001.Srv001RevisaoDadosCadastraisProcedente -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
